name: serena_client
description: Cliente generado de Serverpod para hablarle al backend de Serena.

environment:
  sdk: '^3.8.0'

dependencies:
  serverpod_auth_idp_client: 3.4.12
  serverpod_client: 3.4.12